name: Smart Contract CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies (with legacy peer deps)
        run: npm install --legacy-peer-deps

      - name: 🔨 Compile smart contracts
        run: npx hardhat compile

      - name: 🧪 Run full test suite
        run: npx hardhat test

      - name: 📊 Run gas reporting (optional)
        if: always()
        run: |
          if [ -f hardhat.config.ts ] || [ -f hardhat.config.js ]; then
            npx hardhat test --network hardhat
          fi
